### ISSUE TITLE
Error parsing timestamps

### ISSUE THREAD

**Issue by gronnbeck** [unacast/migrations#3]
When I'm running the migrations multiple times I get the following stacktrace

```
[Starting migration:  2017-03-18 09:10:45.515872865 +0000 UTC]
panic: Failed to scan migration row: sql: Scan error on column index 1: unsupported Scan, storing driver.Value type []uint8 into type *time.Time

goroutine 1 [running]:
github.com/unacast/imporker/vendor/github.com/unacast/migrations.(*Migrator).getExistingMigrations(0xc42000e070, 0x0, 0x0, 0x0)
	/Users/gronnbeck/dev/go/src/github.com/unacast/imporker/vendor/github.com/unacast/migrations/migrations.go:167 +0x4cd
github.com/unacast/imporker/vendor/github.com/unacast/migrations.(*Migrator).Migrate(0xc42000e070, 0x136cd88, 0x136cd90)
	/Users/gronnbeck/dev/go/src/github.com/unacast/imporker/vendor/github.com/unacast/migrations/migrations.go:64 +0x1f3
github.com/unacast/imporker/filetracker.Client.Migrate(0xc4200950e0)
	/Users/gronnbeck/dev/go/src/github.com/unacast/imporker/filetracker/filetracker.go:78 +0x163
main.main()
	/Users/gronnbeck/dev/go/src/github.com/unacast/imporker/main.go:19 +0x64
exit status 2
```

It seems to fail when it tries to parse the timestamps. It expects to get a `time.Time` in return but in reality it returns a `[]uint8` (or a `string`). It panics at this exact [LOC](https://github.com/unacast/migrations/blob/master/migrations.go#L167).

**Comment by gronnbeck** [comment]
I'm running `go v1.8` and `mysql  Ver 14.14 Distrib 5.7.17, for osx10.12 (x86_64) using  EditLine wrapper`

**Comment by gronnbeck** [comment]
Added a hack to `migrations.go`: 

```go
for rows.Next() {
		var (
			file         string
			timestampStr string
		)
		err = rows.Scan(&file, &timestampStr)
		if err != nil {
			panic("Failed to scan migration row: " + err.Error())
		}
		timestamp, err := time.Parse("2006-01-02 15:04:05", timestampStr)
		if err != nil {
			panic(err)
		}
		migrations = append(migrations, migration{file: file, timestamp: timestamp})
	}
```

It's not pretty but it works for now. Let's find the core cause of it. I think I might be misusing MYSQL.

**Comment by gronnbeck** [comment]
I'm going to try this:

https://github.com/go-sql-driver/mysql#timetime-support:
> However, many want to scan MySQL DATE and DATETIME values into time.Time variables, which is the logical opposite in Go to DATE and DATETIME in MySQL. You can do that by changing the internal output type from []byte to time.Time with the DSN parameter parseTime=true. You can set the default time.Time location with the loc DSN parameter.

Maybe add that to the readme?
